### ISSUE TITLE
Baking Fluid Broken (among others).

### ISSUE THREAD

**Issue by jujubeesloco** [ichlubna/blenderScripts#1]
@ichlubna 

The output stops after "Baking Particles --- Frame 250::250".

I believe only particles are baking, though there's no particles to bake. I delete the particle code, and the .py does nothing.

I'm using Blender 2.82 in Windows 10.

-Cheers and thank you.

**Comment by ichlubna** [comment]
@jujubeesloco Hmm thanks for the report. I see that the script is not working in the new Blender version with Mantaflow. I'll try to solve it somehow.

**Comment by ichlubna** [comment]
Opened [bug report](https://developer.blender.org/T75889) at Blender Dev.

**Comment by ichlubna** [comment]
Made some edits in the script due to API changes in db8c6c7. The Blender bug was also fixed.
