### ISSUE TITLE
unable to use ffExport.py

### ISSUE THREAD

**Issue by Lauloque** [ichlubna/blenderScripts#3]
I set my ffmpeg path to where i have ffmpeg.exe, and using any of the examples' presets i just get this error after the render is done:

```python
Python: Traceback (most recent call last):
  File "C:\Users\Roikku\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\ffExport - Copy.py", line 96, in invoke
    self.encodeScene(context)      
  File "C:\Users\Roikku\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\ffExport - Copy.py", line 89, in encodeScene
    raise subprocess.CalledProcessError(pipe.returncode, cmd)
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-f', 'image2pipe', '-c:v', 'png', '-r', '24.0', '-i', '-', '-c:v', 'libx265', '-crf', '28', '-pix_fmt', 'yuv420p', 'example.mkv']' returned non-zero exit status 1.

```

I tried with bot forward and backward slashes, with and without slash at the end of path, with and without ffmpeg.exe. Other than that, i don't know what else to try.

On another note: I reckon it would be a nice quality of life to set the ffmpeg path input ad DIR_PATH or FILE_PATH subtype.

**Comment by ichlubna** [comment]
Hey, sorry for the late reply. I didn't get the notification.
The script is working fine on my PC. Hmm have you tried to run the ffmpeg command from the error message alone in terminal? Maybe without the pipe? Are you able to run ffmpeg from the terminal just by typing `ffmpeg`?
Also added the path input property, good suggestion :-).

**Comment by Lauloque** [comment]
I wouldn't be able to run that command, the file input is unspecified: `-i -`

**Comment by Lauloque** [comment]
Using the new script version, i noticed something else:

With "store frames" disabled, it outputs a single `frame.png` file under `C:\Users\Roikku\AppData\Local\Temp\randomName\`. It looks like it's rendering each frame and saving it with the same name instead of writing one file per frame.

But with "store frames" enabled: the default `./myFrames' leads to an error as soon as the first frame is rendered and written:

```py
Python: Traceback (most recent call last):
  File "C:\Users\Roikku\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\ffExport - Copy.py", line 96, in invoke
    self.encodeScene(context)      
  File "C:\Users\Roikku\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\ffExport - Copy.py", line 84, in encodeScene
    self.encodeRender(context, renderInfo, tempDir, pipe)
  File "C:\Users\Roikku\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\ffExport - Copy.py", line 62, in encodeRender
    with open(renderInfo.filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './myFrames/00001.png'
```
Which is weird because it did created the file in `c:\myFrames\00001.png`

Though, replacing the image path by `c:/myFrames` seems to make the rendering work. Until it wants to run the ffmpeg command.

**Comment by ichlubna** [comment]
True, I was just wondering if the problem was not the missing ffmpeg. But I found a bug now, I didn't use the ffmpeg path at all in the script! Fixed now. Thank you!
In Windows you need to set the ffmpeg path correctly, to something like `ffmpeg.exe` where you have it installed, did you do that? Even if you did it wasn't working before so please try again. ^_^"
The storing of the one temp file is OK.
And about the path, yes I think Linux and Windows use different slashes in the paths / vs \\. So you solved it right I guess.
Sorry for the trouble, I haven't tested the script on other distributions yet.

**Comment by ichlubna** [comment]
Found one more bug on Windows. I had to escape the path. I have now tested it on Windows too and the current version 0d596d4458e167a6b67a66f2876e9d0bd7e56224 seems to be working fine!

**Comment by ichlubna** [comment]
I am closing this @L0Lock since the reported issues seem to be fixed. Feel free to open a new issue if you find another problem. Thanks for the reports!

**Comment by Lauloque** [comment]
Just tested it on my windows machine, it works. Thanks!
